// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: crawler.proto
// Protobuf Java Version: 4.29.0-rc2

package crawler;

public final class Crawler {
  private Crawler() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 0,
      /* suffix= */ "-rc2",
      Crawler.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * <pre>
   * 选取爬取站点
   * </pre>
   *
   * Protobuf enum {@code crawler.Site}
   */
  public enum Site
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * xiaohongshu
     * </pre>
     *
     * <code>XIAOHONGSHU = 0;</code>
     */
    XIAOHONGSHU(0),
    UNRECOGNIZED(-1),
    ;

    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 0,
        /* suffix= */ "-rc2",
        Site.class.getName());
    }
    /**
     * <pre>
     * xiaohongshu
     * </pre>
     *
     * <code>XIAOHONGSHU = 0;</code>
     */
    public static final int XIAOHONGSHU_VALUE = 0;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Site valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static Site forNumber(int value) {
      switch (value) {
        case 0: return XIAOHONGSHU;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Site>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Site> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Site>() {
            public Site findValueByNumber(int number) {
              return Site.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return crawler.Crawler.getDescriptor().getEnumTypes().get(0);
    }

    private static final Site[] VALUES = values();

    public static Site valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Site(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:crawler.Site)
  }

  public interface CrawlRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:crawler.CrawlRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 爬取站点
     * </pre>
     *
     * <code>.crawler.Site site = 1;</code>
     * @return The enum numeric value on the wire for site.
     */
    int getSiteValue();
    /**
     * <pre>
     * 爬取站点
     * </pre>
     *
     * <code>.crawler.Site site = 1;</code>
     * @return The site.
     */
    crawler.Crawler.Site getSite();

    /**
     * <pre>
     * 搜索关键词，例如"南昌大学"
     * </pre>
     *
     * <code>string keyword = 2;</code>
     * @return The keyword.
     */
    java.lang.String getKeyword();
    /**
     * <pre>
     * 搜索关键词，例如"南昌大学"
     * </pre>
     *
     * <code>string keyword = 2;</code>
     * @return The bytes for keyword.
     */
    com.google.protobuf.ByteString
        getKeywordBytes();

    /**
     * <pre>
     * 爬取帖子数量
     * </pre>
     *
     * <code>uint64 post_count = 3;</code>
     * @return The postCount.
     */
    long getPostCount();

    /**
     * <pre>
     * 最少点赞数筛选
     * </pre>
     *
     * <code>uint64 min_likes = 4;</code>
     * @return The minLikes.
     */
    long getMinLikes();

    /**
     * <pre>
     * 每条评论爬取的回复数量
     * </pre>
     *
     * <code>uint64 comment_min_likes = 5;</code>
     * @return The commentMinLikes.
     */
    long getCommentMinLikes();

    /**
     * <pre>
     * 每个帖子爬取的评论数量
     * </pre>
     *
     * <code>uint64 comments_per_post = 6;</code>
     * @return The commentsPerPost.
     */
    long getCommentsPerPost();

    /**
     * <pre>
     * 是否包含评论
     * </pre>
     *
     * <code>bool include_comments = 7;</code>
     * @return The includeComments.
     */
    boolean getIncludeComments();

    /**
     * <pre>
     * 是否爬取图片URL
     * </pre>
     *
     * <code>bool include_images = 8;</code>
     * @return The includeImages.
     */
    boolean getIncludeImages();
  }
  /**
   * <pre>
   * 爬虫请求参数
   * </pre>
   *
   * Protobuf type {@code crawler.CrawlRequest}
   */
  public static final class CrawlRequest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:crawler.CrawlRequest)
      CrawlRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 0,
        /* suffix= */ "-rc2",
        CrawlRequest.class.getName());
    }
    // Use CrawlRequest.newBuilder() to construct.
    private CrawlRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private CrawlRequest() {
      site_ = 0;
      keyword_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return crawler.Crawler.internal_static_crawler_CrawlRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return crawler.Crawler.internal_static_crawler_CrawlRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              crawler.Crawler.CrawlRequest.class, crawler.Crawler.CrawlRequest.Builder.class);
    }

    public static final int SITE_FIELD_NUMBER = 1;
    private int site_ = 0;
    /**
     * <pre>
     * 爬取站点
     * </pre>
     *
     * <code>.crawler.Site site = 1;</code>
     * @return The enum numeric value on the wire for site.
     */
    @java.lang.Override public int getSiteValue() {
      return site_;
    }
    /**
     * <pre>
     * 爬取站点
     * </pre>
     *
     * <code>.crawler.Site site = 1;</code>
     * @return The site.
     */
    @java.lang.Override public crawler.Crawler.Site getSite() {
      crawler.Crawler.Site result = crawler.Crawler.Site.forNumber(site_);
      return result == null ? crawler.Crawler.Site.UNRECOGNIZED : result;
    }

    public static final int KEYWORD_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object keyword_ = "";
    /**
     * <pre>
     * 搜索关键词，例如"南昌大学"
     * </pre>
     *
     * <code>string keyword = 2;</code>
     * @return The keyword.
     */
    @java.lang.Override
    public java.lang.String getKeyword() {
      java.lang.Object ref = keyword_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        keyword_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 搜索关键词，例如"南昌大学"
     * </pre>
     *
     * <code>string keyword = 2;</code>
     * @return The bytes for keyword.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getKeywordBytes() {
      java.lang.Object ref = keyword_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        keyword_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int POST_COUNT_FIELD_NUMBER = 3;
    private long postCount_ = 0L;
    /**
     * <pre>
     * 爬取帖子数量
     * </pre>
     *
     * <code>uint64 post_count = 3;</code>
     * @return The postCount.
     */
    @java.lang.Override
    public long getPostCount() {
      return postCount_;
    }

    public static final int MIN_LIKES_FIELD_NUMBER = 4;
    private long minLikes_ = 0L;
    /**
     * <pre>
     * 最少点赞数筛选
     * </pre>
     *
     * <code>uint64 min_likes = 4;</code>
     * @return The minLikes.
     */
    @java.lang.Override
    public long getMinLikes() {
      return minLikes_;
    }

    public static final int COMMENT_MIN_LIKES_FIELD_NUMBER = 5;
    private long commentMinLikes_ = 0L;
    /**
     * <pre>
     * 每条评论爬取的回复数量
     * </pre>
     *
     * <code>uint64 comment_min_likes = 5;</code>
     * @return The commentMinLikes.
     */
    @java.lang.Override
    public long getCommentMinLikes() {
      return commentMinLikes_;
    }

    public static final int COMMENTS_PER_POST_FIELD_NUMBER = 6;
    private long commentsPerPost_ = 0L;
    /**
     * <pre>
     * 每个帖子爬取的评论数量
     * </pre>
     *
     * <code>uint64 comments_per_post = 6;</code>
     * @return The commentsPerPost.
     */
    @java.lang.Override
    public long getCommentsPerPost() {
      return commentsPerPost_;
    }

    public static final int INCLUDE_COMMENTS_FIELD_NUMBER = 7;
    private boolean includeComments_ = false;
    /**
     * <pre>
     * 是否包含评论
     * </pre>
     *
     * <code>bool include_comments = 7;</code>
     * @return The includeComments.
     */
    @java.lang.Override
    public boolean getIncludeComments() {
      return includeComments_;
    }

    public static final int INCLUDE_IMAGES_FIELD_NUMBER = 8;
    private boolean includeImages_ = false;
    /**
     * <pre>
     * 是否爬取图片URL
     * </pre>
     *
     * <code>bool include_images = 8;</code>
     * @return The includeImages.
     */
    @java.lang.Override
    public boolean getIncludeImages() {
      return includeImages_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (site_ != crawler.Crawler.Site.XIAOHONGSHU.getNumber()) {
        output.writeEnum(1, site_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(keyword_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, keyword_);
      }
      if (postCount_ != 0L) {
        output.writeUInt64(3, postCount_);
      }
      if (minLikes_ != 0L) {
        output.writeUInt64(4, minLikes_);
      }
      if (commentMinLikes_ != 0L) {
        output.writeUInt64(5, commentMinLikes_);
      }
      if (commentsPerPost_ != 0L) {
        output.writeUInt64(6, commentsPerPost_);
      }
      if (includeComments_ != false) {
        output.writeBool(7, includeComments_);
      }
      if (includeImages_ != false) {
        output.writeBool(8, includeImages_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (site_ != crawler.Crawler.Site.XIAOHONGSHU.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, site_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(keyword_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, keyword_);
      }
      if (postCount_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(3, postCount_);
      }
      if (minLikes_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(4, minLikes_);
      }
      if (commentMinLikes_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(5, commentMinLikes_);
      }
      if (commentsPerPost_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(6, commentsPerPost_);
      }
      if (includeComments_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(7, includeComments_);
      }
      if (includeImages_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(8, includeImages_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof crawler.Crawler.CrawlRequest)) {
        return super.equals(obj);
      }
      crawler.Crawler.CrawlRequest other = (crawler.Crawler.CrawlRequest) obj;

      if (site_ != other.site_) return false;
      if (!getKeyword()
          .equals(other.getKeyword())) return false;
      if (getPostCount()
          != other.getPostCount()) return false;
      if (getMinLikes()
          != other.getMinLikes()) return false;
      if (getCommentMinLikes()
          != other.getCommentMinLikes()) return false;
      if (getCommentsPerPost()
          != other.getCommentsPerPost()) return false;
      if (getIncludeComments()
          != other.getIncludeComments()) return false;
      if (getIncludeImages()
          != other.getIncludeImages()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SITE_FIELD_NUMBER;
      hash = (53 * hash) + site_;
      hash = (37 * hash) + KEYWORD_FIELD_NUMBER;
      hash = (53 * hash) + getKeyword().hashCode();
      hash = (37 * hash) + POST_COUNT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getPostCount());
      hash = (37 * hash) + MIN_LIKES_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getMinLikes());
      hash = (37 * hash) + COMMENT_MIN_LIKES_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getCommentMinLikes());
      hash = (37 * hash) + COMMENTS_PER_POST_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getCommentsPerPost());
      hash = (37 * hash) + INCLUDE_COMMENTS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIncludeComments());
      hash = (37 * hash) + INCLUDE_IMAGES_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIncludeImages());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static crawler.Crawler.CrawlRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static crawler.Crawler.CrawlRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static crawler.Crawler.CrawlRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static crawler.Crawler.CrawlRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static crawler.Crawler.CrawlRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static crawler.Crawler.CrawlRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static crawler.Crawler.CrawlRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static crawler.Crawler.CrawlRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static crawler.Crawler.CrawlRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static crawler.Crawler.CrawlRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static crawler.Crawler.CrawlRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static crawler.Crawler.CrawlRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(crawler.Crawler.CrawlRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 爬虫请求参数
     * </pre>
     *
     * Protobuf type {@code crawler.CrawlRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:crawler.CrawlRequest)
        crawler.Crawler.CrawlRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return crawler.Crawler.internal_static_crawler_CrawlRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return crawler.Crawler.internal_static_crawler_CrawlRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                crawler.Crawler.CrawlRequest.class, crawler.Crawler.CrawlRequest.Builder.class);
      }

      // Construct using crawler.Crawler.CrawlRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        site_ = 0;
        keyword_ = "";
        postCount_ = 0L;
        minLikes_ = 0L;
        commentMinLikes_ = 0L;
        commentsPerPost_ = 0L;
        includeComments_ = false;
        includeImages_ = false;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return crawler.Crawler.internal_static_crawler_CrawlRequest_descriptor;
      }

      @java.lang.Override
      public crawler.Crawler.CrawlRequest getDefaultInstanceForType() {
        return crawler.Crawler.CrawlRequest.getDefaultInstance();
      }

      @java.lang.Override
      public crawler.Crawler.CrawlRequest build() {
        crawler.Crawler.CrawlRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public crawler.Crawler.CrawlRequest buildPartial() {
        crawler.Crawler.CrawlRequest result = new crawler.Crawler.CrawlRequest(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(crawler.Crawler.CrawlRequest result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.site_ = site_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.keyword_ = keyword_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.postCount_ = postCount_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.minLikes_ = minLikes_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.commentMinLikes_ = commentMinLikes_;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.commentsPerPost_ = commentsPerPost_;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.includeComments_ = includeComments_;
        }
        if (((from_bitField0_ & 0x00000080) != 0)) {
          result.includeImages_ = includeImages_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof crawler.Crawler.CrawlRequest) {
          return mergeFrom((crawler.Crawler.CrawlRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(crawler.Crawler.CrawlRequest other) {
        if (other == crawler.Crawler.CrawlRequest.getDefaultInstance()) return this;
        if (other.site_ != 0) {
          setSiteValue(other.getSiteValue());
        }
        if (!other.getKeyword().isEmpty()) {
          keyword_ = other.keyword_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (other.getPostCount() != 0L) {
          setPostCount(other.getPostCount());
        }
        if (other.getMinLikes() != 0L) {
          setMinLikes(other.getMinLikes());
        }
        if (other.getCommentMinLikes() != 0L) {
          setCommentMinLikes(other.getCommentMinLikes());
        }
        if (other.getCommentsPerPost() != 0L) {
          setCommentsPerPost(other.getCommentsPerPost());
        }
        if (other.getIncludeComments() != false) {
          setIncludeComments(other.getIncludeComments());
        }
        if (other.getIncludeImages() != false) {
          setIncludeImages(other.getIncludeImages());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                site_ = input.readEnum();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                keyword_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 24: {
                postCount_ = input.readUInt64();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 32: {
                minLikes_ = input.readUInt64();
                bitField0_ |= 0x00000008;
                break;
              } // case 32
              case 40: {
                commentMinLikes_ = input.readUInt64();
                bitField0_ |= 0x00000010;
                break;
              } // case 40
              case 48: {
                commentsPerPost_ = input.readUInt64();
                bitField0_ |= 0x00000020;
                break;
              } // case 48
              case 56: {
                includeComments_ = input.readBool();
                bitField0_ |= 0x00000040;
                break;
              } // case 56
              case 64: {
                includeImages_ = input.readBool();
                bitField0_ |= 0x00000080;
                break;
              } // case 64
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int site_ = 0;
      /**
       * <pre>
       * 爬取站点
       * </pre>
       *
       * <code>.crawler.Site site = 1;</code>
       * @return The enum numeric value on the wire for site.
       */
      @java.lang.Override public int getSiteValue() {
        return site_;
      }
      /**
       * <pre>
       * 爬取站点
       * </pre>
       *
       * <code>.crawler.Site site = 1;</code>
       * @param value The enum numeric value on the wire for site to set.
       * @return This builder for chaining.
       */
      public Builder setSiteValue(int value) {
        site_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 爬取站点
       * </pre>
       *
       * <code>.crawler.Site site = 1;</code>
       * @return The site.
       */
      @java.lang.Override
      public crawler.Crawler.Site getSite() {
        crawler.Crawler.Site result = crawler.Crawler.Site.forNumber(site_);
        return result == null ? crawler.Crawler.Site.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       * 爬取站点
       * </pre>
       *
       * <code>.crawler.Site site = 1;</code>
       * @param value The site to set.
       * @return This builder for chaining.
       */
      public Builder setSite(crawler.Crawler.Site value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        site_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 爬取站点
       * </pre>
       *
       * <code>.crawler.Site site = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSite() {
        bitField0_ = (bitField0_ & ~0x00000001);
        site_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object keyword_ = "";
      /**
       * <pre>
       * 搜索关键词，例如"南昌大学"
       * </pre>
       *
       * <code>string keyword = 2;</code>
       * @return The keyword.
       */
      public java.lang.String getKeyword() {
        java.lang.Object ref = keyword_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          keyword_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 搜索关键词，例如"南昌大学"
       * </pre>
       *
       * <code>string keyword = 2;</code>
       * @return The bytes for keyword.
       */
      public com.google.protobuf.ByteString
          getKeywordBytes() {
        java.lang.Object ref = keyword_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          keyword_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 搜索关键词，例如"南昌大学"
       * </pre>
       *
       * <code>string keyword = 2;</code>
       * @param value The keyword to set.
       * @return This builder for chaining.
       */
      public Builder setKeyword(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        keyword_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 搜索关键词，例如"南昌大学"
       * </pre>
       *
       * <code>string keyword = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearKeyword() {
        keyword_ = getDefaultInstance().getKeyword();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 搜索关键词，例如"南昌大学"
       * </pre>
       *
       * <code>string keyword = 2;</code>
       * @param value The bytes for keyword to set.
       * @return This builder for chaining.
       */
      public Builder setKeywordBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        keyword_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private long postCount_ ;
      /**
       * <pre>
       * 爬取帖子数量
       * </pre>
       *
       * <code>uint64 post_count = 3;</code>
       * @return The postCount.
       */
      @java.lang.Override
      public long getPostCount() {
        return postCount_;
      }
      /**
       * <pre>
       * 爬取帖子数量
       * </pre>
       *
       * <code>uint64 post_count = 3;</code>
       * @param value The postCount to set.
       * @return This builder for chaining.
       */
      public Builder setPostCount(long value) {

        postCount_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 爬取帖子数量
       * </pre>
       *
       * <code>uint64 post_count = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearPostCount() {
        bitField0_ = (bitField0_ & ~0x00000004);
        postCount_ = 0L;
        onChanged();
        return this;
      }

      private long minLikes_ ;
      /**
       * <pre>
       * 最少点赞数筛选
       * </pre>
       *
       * <code>uint64 min_likes = 4;</code>
       * @return The minLikes.
       */
      @java.lang.Override
      public long getMinLikes() {
        return minLikes_;
      }
      /**
       * <pre>
       * 最少点赞数筛选
       * </pre>
       *
       * <code>uint64 min_likes = 4;</code>
       * @param value The minLikes to set.
       * @return This builder for chaining.
       */
      public Builder setMinLikes(long value) {

        minLikes_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 最少点赞数筛选
       * </pre>
       *
       * <code>uint64 min_likes = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearMinLikes() {
        bitField0_ = (bitField0_ & ~0x00000008);
        minLikes_ = 0L;
        onChanged();
        return this;
      }

      private long commentMinLikes_ ;
      /**
       * <pre>
       * 每条评论爬取的回复数量
       * </pre>
       *
       * <code>uint64 comment_min_likes = 5;</code>
       * @return The commentMinLikes.
       */
      @java.lang.Override
      public long getCommentMinLikes() {
        return commentMinLikes_;
      }
      /**
       * <pre>
       * 每条评论爬取的回复数量
       * </pre>
       *
       * <code>uint64 comment_min_likes = 5;</code>
       * @param value The commentMinLikes to set.
       * @return This builder for chaining.
       */
      public Builder setCommentMinLikes(long value) {

        commentMinLikes_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 每条评论爬取的回复数量
       * </pre>
       *
       * <code>uint64 comment_min_likes = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearCommentMinLikes() {
        bitField0_ = (bitField0_ & ~0x00000010);
        commentMinLikes_ = 0L;
        onChanged();
        return this;
      }

      private long commentsPerPost_ ;
      /**
       * <pre>
       * 每个帖子爬取的评论数量
       * </pre>
       *
       * <code>uint64 comments_per_post = 6;</code>
       * @return The commentsPerPost.
       */
      @java.lang.Override
      public long getCommentsPerPost() {
        return commentsPerPost_;
      }
      /**
       * <pre>
       * 每个帖子爬取的评论数量
       * </pre>
       *
       * <code>uint64 comments_per_post = 6;</code>
       * @param value The commentsPerPost to set.
       * @return This builder for chaining.
       */
      public Builder setCommentsPerPost(long value) {

        commentsPerPost_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 每个帖子爬取的评论数量
       * </pre>
       *
       * <code>uint64 comments_per_post = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearCommentsPerPost() {
        bitField0_ = (bitField0_ & ~0x00000020);
        commentsPerPost_ = 0L;
        onChanged();
        return this;
      }

      private boolean includeComments_ ;
      /**
       * <pre>
       * 是否包含评论
       * </pre>
       *
       * <code>bool include_comments = 7;</code>
       * @return The includeComments.
       */
      @java.lang.Override
      public boolean getIncludeComments() {
        return includeComments_;
      }
      /**
       * <pre>
       * 是否包含评论
       * </pre>
       *
       * <code>bool include_comments = 7;</code>
       * @param value The includeComments to set.
       * @return This builder for chaining.
       */
      public Builder setIncludeComments(boolean value) {

        includeComments_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 是否包含评论
       * </pre>
       *
       * <code>bool include_comments = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearIncludeComments() {
        bitField0_ = (bitField0_ & ~0x00000040);
        includeComments_ = false;
        onChanged();
        return this;
      }

      private boolean includeImages_ ;
      /**
       * <pre>
       * 是否爬取图片URL
       * </pre>
       *
       * <code>bool include_images = 8;</code>
       * @return The includeImages.
       */
      @java.lang.Override
      public boolean getIncludeImages() {
        return includeImages_;
      }
      /**
       * <pre>
       * 是否爬取图片URL
       * </pre>
       *
       * <code>bool include_images = 8;</code>
       * @param value The includeImages to set.
       * @return This builder for chaining.
       */
      public Builder setIncludeImages(boolean value) {

        includeImages_ = value;
        bitField0_ |= 0x00000080;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 是否爬取图片URL
       * </pre>
       *
       * <code>bool include_images = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearIncludeImages() {
        bitField0_ = (bitField0_ & ~0x00000080);
        includeImages_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:crawler.CrawlRequest)
    }

    // @@protoc_insertion_point(class_scope:crawler.CrawlRequest)
    private static final crawler.Crawler.CrawlRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new crawler.Crawler.CrawlRequest();
    }

    public static crawler.Crawler.CrawlRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CrawlRequest>
        PARSER = new com.google.protobuf.AbstractParser<CrawlRequest>() {
      @java.lang.Override
      public CrawlRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<CrawlRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CrawlRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public crawler.Crawler.CrawlRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CrawlResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:crawler.CrawlResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 任务ID，用于后续查询状态
     * </pre>
     *
     * <code>string task_id = 1;</code>
     * @return The taskId.
     */
    java.lang.String getTaskId();
    /**
     * <pre>
     * 任务ID，用于后续查询状态
     * </pre>
     *
     * <code>string task_id = 1;</code>
     * @return The bytes for taskId.
     */
    com.google.protobuf.ByteString
        getTaskIdBytes();

    /**
     * <pre>
     * 任务是否成功启动
     * </pre>
     *
     * <code>bool success = 2;</code>
     * @return The success.
     */
    boolean getSuccess();

    /**
     * <pre>
     * 相关信息或错误消息
     * </pre>
     *
     * <code>string message = 3;</code>
     * @return The message.
     */
    java.lang.String getMessage();
    /**
     * <pre>
     * 相关信息或错误消息
     * </pre>
     *
     * <code>string message = 3;</code>
     * @return The bytes for message.
     */
    com.google.protobuf.ByteString
        getMessageBytes();
  }
  /**
   * <pre>
   * 爬虫响应
   * </pre>
   *
   * Protobuf type {@code crawler.CrawlResponse}
   */
  public static final class CrawlResponse extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:crawler.CrawlResponse)
      CrawlResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 0,
        /* suffix= */ "-rc2",
        CrawlResponse.class.getName());
    }
    // Use CrawlResponse.newBuilder() to construct.
    private CrawlResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private CrawlResponse() {
      taskId_ = "";
      message_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return crawler.Crawler.internal_static_crawler_CrawlResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return crawler.Crawler.internal_static_crawler_CrawlResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              crawler.Crawler.CrawlResponse.class, crawler.Crawler.CrawlResponse.Builder.class);
    }

    public static final int TASK_ID_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object taskId_ = "";
    /**
     * <pre>
     * 任务ID，用于后续查询状态
     * </pre>
     *
     * <code>string task_id = 1;</code>
     * @return The taskId.
     */
    @java.lang.Override
    public java.lang.String getTaskId() {
      java.lang.Object ref = taskId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        taskId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 任务ID，用于后续查询状态
     * </pre>
     *
     * <code>string task_id = 1;</code>
     * @return The bytes for taskId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTaskIdBytes() {
      java.lang.Object ref = taskId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        taskId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SUCCESS_FIELD_NUMBER = 2;
    private boolean success_ = false;
    /**
     * <pre>
     * 任务是否成功启动
     * </pre>
     *
     * <code>bool success = 2;</code>
     * @return The success.
     */
    @java.lang.Override
    public boolean getSuccess() {
      return success_;
    }

    public static final int MESSAGE_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object message_ = "";
    /**
     * <pre>
     * 相关信息或错误消息
     * </pre>
     *
     * <code>string message = 3;</code>
     * @return The message.
     */
    @java.lang.Override
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 相关信息或错误消息
     * </pre>
     *
     * <code>string message = 3;</code>
     * @return The bytes for message.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(taskId_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, taskId_);
      }
      if (success_ != false) {
        output.writeBool(2, success_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(message_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, message_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(taskId_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, taskId_);
      }
      if (success_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, success_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(message_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(3, message_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof crawler.Crawler.CrawlResponse)) {
        return super.equals(obj);
      }
      crawler.Crawler.CrawlResponse other = (crawler.Crawler.CrawlResponse) obj;

      if (!getTaskId()
          .equals(other.getTaskId())) return false;
      if (getSuccess()
          != other.getSuccess()) return false;
      if (!getMessage()
          .equals(other.getMessage())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TASK_ID_FIELD_NUMBER;
      hash = (53 * hash) + getTaskId().hashCode();
      hash = (37 * hash) + SUCCESS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getSuccess());
      hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getMessage().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static crawler.Crawler.CrawlResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static crawler.Crawler.CrawlResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static crawler.Crawler.CrawlResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static crawler.Crawler.CrawlResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static crawler.Crawler.CrawlResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static crawler.Crawler.CrawlResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static crawler.Crawler.CrawlResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static crawler.Crawler.CrawlResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static crawler.Crawler.CrawlResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static crawler.Crawler.CrawlResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static crawler.Crawler.CrawlResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static crawler.Crawler.CrawlResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(crawler.Crawler.CrawlResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 爬虫响应
     * </pre>
     *
     * Protobuf type {@code crawler.CrawlResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:crawler.CrawlResponse)
        crawler.Crawler.CrawlResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return crawler.Crawler.internal_static_crawler_CrawlResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return crawler.Crawler.internal_static_crawler_CrawlResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                crawler.Crawler.CrawlResponse.class, crawler.Crawler.CrawlResponse.Builder.class);
      }

      // Construct using crawler.Crawler.CrawlResponse.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        taskId_ = "";
        success_ = false;
        message_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return crawler.Crawler.internal_static_crawler_CrawlResponse_descriptor;
      }

      @java.lang.Override
      public crawler.Crawler.CrawlResponse getDefaultInstanceForType() {
        return crawler.Crawler.CrawlResponse.getDefaultInstance();
      }

      @java.lang.Override
      public crawler.Crawler.CrawlResponse build() {
        crawler.Crawler.CrawlResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public crawler.Crawler.CrawlResponse buildPartial() {
        crawler.Crawler.CrawlResponse result = new crawler.Crawler.CrawlResponse(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(crawler.Crawler.CrawlResponse result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.taskId_ = taskId_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.success_ = success_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.message_ = message_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof crawler.Crawler.CrawlResponse) {
          return mergeFrom((crawler.Crawler.CrawlResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(crawler.Crawler.CrawlResponse other) {
        if (other == crawler.Crawler.CrawlResponse.getDefaultInstance()) return this;
        if (!other.getTaskId().isEmpty()) {
          taskId_ = other.taskId_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.getSuccess() != false) {
          setSuccess(other.getSuccess());
        }
        if (!other.getMessage().isEmpty()) {
          message_ = other.message_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                taskId_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 16: {
                success_ = input.readBool();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 26: {
                message_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object taskId_ = "";
      /**
       * <pre>
       * 任务ID，用于后续查询状态
       * </pre>
       *
       * <code>string task_id = 1;</code>
       * @return The taskId.
       */
      public java.lang.String getTaskId() {
        java.lang.Object ref = taskId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          taskId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 任务ID，用于后续查询状态
       * </pre>
       *
       * <code>string task_id = 1;</code>
       * @return The bytes for taskId.
       */
      public com.google.protobuf.ByteString
          getTaskIdBytes() {
        java.lang.Object ref = taskId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          taskId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 任务ID，用于后续查询状态
       * </pre>
       *
       * <code>string task_id = 1;</code>
       * @param value The taskId to set.
       * @return This builder for chaining.
       */
      public Builder setTaskId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        taskId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 任务ID，用于后续查询状态
       * </pre>
       *
       * <code>string task_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTaskId() {
        taskId_ = getDefaultInstance().getTaskId();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 任务ID，用于后续查询状态
       * </pre>
       *
       * <code>string task_id = 1;</code>
       * @param value The bytes for taskId to set.
       * @return This builder for chaining.
       */
      public Builder setTaskIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        taskId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private boolean success_ ;
      /**
       * <pre>
       * 任务是否成功启动
       * </pre>
       *
       * <code>bool success = 2;</code>
       * @return The success.
       */
      @java.lang.Override
      public boolean getSuccess() {
        return success_;
      }
      /**
       * <pre>
       * 任务是否成功启动
       * </pre>
       *
       * <code>bool success = 2;</code>
       * @param value The success to set.
       * @return This builder for chaining.
       */
      public Builder setSuccess(boolean value) {

        success_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 任务是否成功启动
       * </pre>
       *
       * <code>bool success = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearSuccess() {
        bitField0_ = (bitField0_ & ~0x00000002);
        success_ = false;
        onChanged();
        return this;
      }

      private java.lang.Object message_ = "";
      /**
       * <pre>
       * 相关信息或错误消息
       * </pre>
       *
       * <code>string message = 3;</code>
       * @return The message.
       */
      public java.lang.String getMessage() {
        java.lang.Object ref = message_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          message_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 相关信息或错误消息
       * </pre>
       *
       * <code>string message = 3;</code>
       * @return The bytes for message.
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        java.lang.Object ref = message_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 相关信息或错误消息
       * </pre>
       *
       * <code>string message = 3;</code>
       * @param value The message to set.
       * @return This builder for chaining.
       */
      public Builder setMessage(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        message_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 相关信息或错误消息
       * </pre>
       *
       * <code>string message = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearMessage() {
        message_ = getDefaultInstance().getMessage();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 相关信息或错误消息
       * </pre>
       *
       * <code>string message = 3;</code>
       * @param value The bytes for message to set.
       * @return This builder for chaining.
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        message_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:crawler.CrawlResponse)
    }

    // @@protoc_insertion_point(class_scope:crawler.CrawlResponse)
    private static final crawler.Crawler.CrawlResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new crawler.Crawler.CrawlResponse();
    }

    public static crawler.Crawler.CrawlResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CrawlResponse>
        PARSER = new com.google.protobuf.AbstractParser<CrawlResponse>() {
      @java.lang.Override
      public CrawlResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<CrawlResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CrawlResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public crawler.Crawler.CrawlResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_crawler_CrawlRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_crawler_CrawlRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_crawler_CrawlResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_crawler_CrawlResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rcrawler.proto\022\007crawler\"\313\001\n\014CrawlReques" +
      "t\022\033\n\004site\030\001 \001(\0162\r.crawler.Site\022\017\n\007keywor" +
      "d\030\002 \001(\t\022\022\n\npost_count\030\003 \001(\004\022\021\n\tmin_likes" +
      "\030\004 \001(\004\022\031\n\021comment_min_likes\030\005 \001(\004\022\031\n\021com" +
      "ments_per_post\030\006 \001(\004\022\030\n\020include_comments" +
      "\030\007 \001(\010\022\026\n\016include_images\030\010 \001(\010\"B\n\rCrawlR" +
      "esponse\022\017\n\007task_id\030\001 \001(\t\022\017\n\007success\030\002 \001(" +
      "\010\022\017\n\007message\030\003 \001(\t*\027\n\004Site\022\017\n\013XIAOHONGSH" +
      "U\020\0002M\n\016CrawlerService\022;\n\nStartCrawl\022\025.cr" +
      "awler.CrawlRequest\032\026.crawler.CrawlRespon" +
      "seB\tZ\007./protob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_crawler_CrawlRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_crawler_CrawlRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_crawler_CrawlRequest_descriptor,
        new java.lang.String[] { "Site", "Keyword", "PostCount", "MinLikes", "CommentMinLikes", "CommentsPerPost", "IncludeComments", "IncludeImages", });
    internal_static_crawler_CrawlResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_crawler_CrawlResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_crawler_CrawlResponse_descriptor,
        new java.lang.String[] { "TaskId", "Success", "Message", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
