// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.4

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"
	
	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	commentsFieldNames          = builder.RawFieldNames(&Comments{})
	commentsRows                = strings.Join(commentsFieldNames, ",")
	commentsRowsExpectAutoSet   = strings.Join(stringx.Remove(commentsFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	commentsRowsWithPlaceHolder = strings.Join(stringx.Remove(commentsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheGradinsightCommentsIdPrefix = "cache:gradinsight:comments:id:"
)

type (
	commentsModel interface {
		Insert(ctx context.Context, data *Comments) (sql.Result, error)
		FindOne(ctx context.Context, id string) (*Comments, error)
		Update(ctx context.Context, data *Comments) error
		Delete(ctx context.Context, id string) error
	}

	defaultCommentsModel struct {
		sqlc.CachedConn
		table string
	}

	Comments struct {
		Id          string         `db:"id"`           // 评论ID
		TaskId      string         `db:"task_id"`      // 任务ID
		PostId      string         `db:"post_id"`      // 帖子ID
		Commenter   string         `db:"commenter"`    // 评论者
		CommentTime time.Time      `db:"comment_time"` // 评论时间
		Location    sql.NullString `db:"location"`     // 位置
		Content     string         `db:"content"`      // 评论内容
		LikeCount   uint64         `db:"like_count"`   // 点赞数
		ReplyCount  uint64         `db:"reply_count"`  // 回复数
		CreatedAt   time.Time      `db:"created_at"`   // 创建时间
	}
)

func newCommentsModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultCommentsModel {
	return &defaultCommentsModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`comments`",
	}
}

func (m *defaultCommentsModel) Delete(ctx context.Context, id string) error {
	gradinsightCommentsIdKey := fmt.Sprintf("%s%v", cacheGradinsightCommentsIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, gradinsightCommentsIdKey)
	return err
}

func (m *defaultCommentsModel) FindOne(ctx context.Context, id string) (*Comments, error) {
	gradinsightCommentsIdKey := fmt.Sprintf("%s%v", cacheGradinsightCommentsIdPrefix, id)
	var resp Comments
	err := m.QueryRowCtx(ctx, &resp, gradinsightCommentsIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", commentsRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCommentsModel) Insert(ctx context.Context, data *Comments) (sql.Result, error) {
	gradinsightCommentsIdKey := fmt.Sprintf("%s%v", cacheGradinsightCommentsIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, commentsRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Id, data.TaskId, data.PostId, data.Commenter, data.CommentTime, data.Location, data.Content, data.LikeCount, data.ReplyCount)
	}, gradinsightCommentsIdKey)
	return ret, err
}

func (m *defaultCommentsModel) Update(ctx context.Context, data *Comments) error {
	gradinsightCommentsIdKey := fmt.Sprintf("%s%v", cacheGradinsightCommentsIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, commentsRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.TaskId, data.PostId, data.Commenter, data.CommentTime, data.Location, data.Content, data.LikeCount, data.ReplyCount, data.Id)
	}, gradinsightCommentsIdKey)
	return err
}

func (m *defaultCommentsModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheGradinsightCommentsIdPrefix, primary)
}

func (m *defaultCommentsModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", commentsRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultCommentsModel) tableName() string {
	return m.table
}
