// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.4

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"
	
	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	postsFieldNames          = builder.RawFieldNames(&Posts{})
	postsRows                = strings.Join(postsFieldNames, ",")
	postsRowsExpectAutoSet   = strings.Join(stringx.Remove(postsFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	postsRowsWithPlaceHolder = strings.Join(stringx.Remove(postsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheGradinsightPostsIdPrefix = "cache:gradinsight:posts:id:"
)

type (
	postsModel interface {
		Insert(ctx context.Context, data *Posts) (sql.Result, error)
		FindOne(ctx context.Context, id string) (*Posts, error)
		Update(ctx context.Context, data *Posts) error
		Delete(ctx context.Context, id string) error
	}

	defaultPostsModel struct {
		sqlc.CachedConn
		table string
	}

	Posts struct {
		Id           string         `db:"id"`            // 帖子ID
		TaskId       string         `db:"task_id"`       // 任务ID
		Title        string         `db:"title"`         // 帖子标题
		Poster       string         `db:"poster"`        // 发帖人
		PostTime     time.Time      `db:"post_time"`     // 发帖时间
		Location     sql.NullString `db:"location"`      // 位置
		Link         string         `db:"link"`          // 帖子链接
		Tags         sql.NullString `db:"tags"`          // 标签数组
		LikeCount    uint64         `db:"like_count"`    // 点赞数
		CommentCount uint64         `db:"comment_count"` // 评论数
		CollectCount uint64         `db:"collect_count"` // 收藏数
		ImageUrls    sql.NullString `db:"image_urls"`    // 图片URL数组
		CreatedAt    time.Time      `db:"created_at"`    // 创建时间
		UpdatedAt    time.Time      `db:"updated_at"`    // 更新时间
	}
)

func newPostsModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultPostsModel {
	return &defaultPostsModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`posts`",
	}
}

func (m *defaultPostsModel) Delete(ctx context.Context, id string) error {
	gradinsightPostsIdKey := fmt.Sprintf("%s%v", cacheGradinsightPostsIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, gradinsightPostsIdKey)
	return err
}

func (m *defaultPostsModel) FindOne(ctx context.Context, id string) (*Posts, error) {
	gradinsightPostsIdKey := fmt.Sprintf("%s%v", cacheGradinsightPostsIdPrefix, id)
	var resp Posts
	err := m.QueryRowCtx(ctx, &resp, gradinsightPostsIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", postsRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPostsModel) Insert(ctx context.Context, data *Posts) (sql.Result, error) {
	gradinsightPostsIdKey := fmt.Sprintf("%s%v", cacheGradinsightPostsIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, postsRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Id, data.TaskId, data.Title, data.Poster, data.PostTime, data.Location, data.Link, data.Tags, data.LikeCount, data.CommentCount, data.CollectCount, data.ImageUrls)
	}, gradinsightPostsIdKey)
	return ret, err
}

func (m *defaultPostsModel) Update(ctx context.Context, data *Posts) error {
	gradinsightPostsIdKey := fmt.Sprintf("%s%v", cacheGradinsightPostsIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, postsRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.TaskId, data.Title, data.Poster, data.PostTime, data.Location, data.Link, data.Tags, data.LikeCount, data.CommentCount, data.CollectCount, data.ImageUrls, data.Id)
	}, gradinsightPostsIdKey)
	return err
}

func (m *defaultPostsModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheGradinsightPostsIdPrefix, primary)
}

func (m *defaultPostsModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", postsRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultPostsModel) tableName() string {
	return m.table
}
