// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.4

package model

import (
	"context"
	"database/sql"
	"fmt"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
)

var (
	tasksFieldNames          = builder.RawFieldNames(&Tasks{})
	tasksRows                = "`id`,`status`,`posts_collected`,`start_time`,`end_time`,`error_msg`,`site`,`keyword`,`post_count`,`min_likes`,`comment_min_likes`,`comments_per_post`,`include_comments`,`include_images`,`created_at`,`updated_at`"
	tasksRowsExpectAutoSet   = "`id`,`status`,`posts_collected`,`start_time`,`end_time`,`error_msg`,`site`,`keyword`,`post_count`,`min_likes`,`comment_min_likes`,`comments_per_post`,`include_comments`,`include_images`"
	tasksRowsWithPlaceHolder = "`status`=?,`posts_collected`=?,`start_time`=?,`end_time`=?,`error_msg`=?,`site`=?,`keyword`=?,`post_count`=?,`min_likes`=?,`comment_min_likes`=?,`comments_per_post`=?,`include_comments`=?,`include_images`=? where `id`=?"

	cacheGradinsightTasksIdPrefix = "cache:gradinsight:tasks:id:"
)

type (
	tasksModel interface {
		Insert(ctx context.Context, data *Tasks) (sql.Result, error)
		FindOne(ctx context.Context, id string) (*Tasks, error)
		Update(ctx context.Context, data *Tasks) error
		Delete(ctx context.Context, id string) error
	}

	defaultTasksModel struct {
		sqlc.CachedConn
		table string
	}

	Tasks struct {
		Id              string         `db:"id"`                // 任务ID
		Status          int64          `db:"status"`            // 任务状态: 0-已完成, 1-失败, 2-运行中, 3-待处理, 4-分治
		PostsCollected  uint64         `db:"posts_collected"`   // 已收集的帖子数
		StartTime       time.Time      `db:"start_time"`        // 开始时间
		EndTime         sql.NullTime   `db:"end_time"`          // 结束时间
		ErrorMsg        sql.NullString `db:"error_msg"`         // 错误信息
		Site            int64          `db:"site"`              // 站点类型
		Keyword         string         `db:"keyword"`           // 关键词
		PostCount       uint64         `db:"post_count"`        // 帖子数量
		MinLikes        uint64         `db:"min_likes"`         // 最小点赞数
		CommentMinLikes uint64         `db:"comment_min_likes"` // 评论最小点赞数
		CommentsPerPost uint64         `db:"comments_per_post"` // 每个帖子的评论数
		IncludeComments int64          `db:"include_comments"`  // 是否包含评论
		IncludeImages   int64          `db:"include_images"`    // 是否包含图片
		CreatedAt       time.Time      `db:"created_at"`        // 创建时间
		UpdatedAt       time.Time      `db:"updated_at"`        // 更新时间
	}
)

func newTasksModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultTasksModel {
	return &defaultTasksModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`tasks`",
	}
}

func (m *defaultTasksModel) Delete(ctx context.Context, id string) error {
	gradinsightTasksIdKey := fmt.Sprintf("%s%v", cacheGradinsightTasksIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, gradinsightTasksIdKey)
	return err
}

func (m *defaultTasksModel) FindOne(ctx context.Context, id string) (*Tasks, error) {
	gradinsightTasksIdKey := fmt.Sprintf("%s%v", cacheGradinsightTasksIdPrefix, id)
	var resp Tasks
	err := m.QueryRowCtx(ctx, &resp, gradinsightTasksIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", tasksRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTasksModel) Insert(ctx context.Context, data *Tasks) (sql.Result, error) {
	gradinsightTasksIdKey := fmt.Sprintf("%s%v", cacheGradinsightTasksIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, tasksRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Id, data.Status, data.PostsCollected, data.StartTime, data.EndTime, data.ErrorMsg, data.Site, data.Keyword, data.PostCount, data.MinLikes, data.CommentMinLikes, data.CommentsPerPost, data.IncludeComments, data.IncludeImages)
	}, gradinsightTasksIdKey)
	return ret, err
}

func (m *defaultTasksModel) Update(ctx context.Context, data *Tasks) error {
	gradinsightTasksIdKey := fmt.Sprintf("%s%v", cacheGradinsightTasksIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s", m.table, tasksRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.Status, data.PostsCollected, data.StartTime, data.EndTime, data.ErrorMsg, data.Site, data.Keyword, data.PostCount, data.MinLikes, data.CommentMinLikes, data.CommentsPerPost, data.IncludeComments, data.IncludeImages, data.Id)
	}, gradinsightTasksIdKey)
	return err
}

func (m *defaultTasksModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheGradinsightTasksIdPrefix, primary)
}

func (m *defaultTasksModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", tasksRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultTasksModel) tableName() string {
	return m.table
}
